api_platform:
    title: Fastfony API (public & internal)
    version: 0.3.3
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    defaults:
        stateless: false # API is used by admin (stateful) and also by others users (stateless)
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    oauth:
        enabled: true
        clientId: ''
        clientSecret: ''
        type: 'oauth2'
        flow: 'authorizationCode'
        tokenUrl: '/token'
        authorizationUrl: '/authorize'
        scopes: { email: 'email', roles: 'roles', profile: 'profile' }
    mapping:
        paths:
            - '%kernel.project_dir%/src/ApiResource'
            - '%kernel.project_dir%/src/Entity'

when@prod:
    api_platform:
        enable_docs: false
        enable_swagger_ui: false
        enable_re_doc: false
        enable_swagger: false
        enable_entrypoint: false
