framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/assets/locales'
        providers:

when@test:
    framework:
        translator:
            fallbacks: ['en']
