twig:
    file_name_pattern: '*.twig'
    globals:
        app_name: '%env(database:APP_NAME)%'
        app_icon_filepath: '%env(database:APP_ICON_FILEPATH)%'
        registration_background_image_url: '%env(database:REGISTRATION_BACKGROUND_IMAGE_URL)%'
        registration_enabled: '%env(default:default_registration_enabled:bool:database:REGISTRATION_ENABLED)%'
    
    form_themes:
        - 'form/custom_errors.html.twig'

when@test:
    twig:
        strict_variables: true
