<?php

declare(strict_types=1);

namespace App\Entity\Product;

use App\Entity\BlameableEntity;
use App\Entity\CommonProperties;
use App\Repository\Product\PriceRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Twig\Extra\Intl\IntlExtension;

#[ORM\Entity(repositoryClass: PriceRepository::class)]
class Price
{
    use BlameableEntity;
    use CommonProperties\Description;
    use CommonProperties\Required\AutoGeneratedId;
    use CommonProperties\Required\Enabled;
    use TimestampableEntity;

    #[ORM\Column]
    private ?float $unitAmount = null;

    #[ORM\Column(length: 3)]
    private ?string $currency = null;

    #[ORM\ManyToOne(inversedBy: 'prices')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product = null;

    public function __toString(): string
    {
        return ($this->isEnabled() ? '✅' : '❌').' '
            .(new IntlExtension())->formatCurrency($this->getUnitAmount(), $this->getCurrency());
    }

    public function getUnitAmount(): ?float
    {
        return $this->unitAmount;
    }

    public function setUnitAmount(float $unitAmount): static
    {
        $this->unitAmount = $unitAmount;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(string $currency): static
    {
        $this->currency = $currency;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(Product $product): static
    {
        $this->product = $product;

        return $this;
    }
}
