<?php

declare(strict_types=1);

namespace App\Entity\Product;

use App\Entity\BlameableEntity;
use App\Entity\CommonProperties;
use App\Repository\Product\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[Gedmo\Loggable(logEntryClass: ProductLogEntry::class)]
class Product
{
    use BlameableEntity;
    use CommonProperties\Description;
    use CommonProperties\MetaRobots;
    use CommonProperties\Required\AutoGeneratedId;
    use CommonProperties\Required\Enabled;
    use CommonProperties\Required\Name;
    use CommonProperties\Seo;
    use TimestampableEntity;

    #[Gedmo\Slug(fields: ['name'], updatable: false)]
    #[Gedmo\Versioned]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    /**
     * @var Collection<int, Price>
     */
    #[ORM\OneToMany(
        targetEntity: Price::class,
        mappedBy: 'product',
        cascade: ['persist'],
        orphanRemoval: true,
    )]
    private Collection $prices;

    public function __construct()
    {
        $this->prices = new ArrayCollection();
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Price>
     */
    public function getPrices(): Collection
    {
        return $this->prices;
    }

    public function addPrice(Price $price): static
    {
        if (!$this->prices->contains($price)) {
            $this->prices->add($price);
            $price->setProduct($this);
        }

        return $this;
    }

    public function removePrice(Price $price): static
    {
        $this->prices->removeElement($price);

        return $this;
    }
}
