pro_controllers:
    resource: '../../src/Pro/Controller/'
    type: attribute

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
        prefix: /_error
