controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login_check:
    path: /login_check

_translation_edit_in_place:
    resource: '@TranslationBundle/Resources/config/routing_edit_in_place.yaml'
    prefix: /admin
    
api_doc:
    path: /api/docs
    controller: api_platform.action.documentation
    condition: "'%kernel.environment%' != 'prod'"
